 #==== Debian ====
- block:
  - name: install sudo,mc,net-tools on Debian
    apt: name=sudo,mc,net-tools,xz-utils state=latest install_recommends=yes update_cache=yes
#  - name: Set user to group sudo
#    shell:
#      cmd: /usr/sbin/usermod -aG sudo '{{ username }}'
#    register: output
  - name: Set user with builtin module
    ansible.builtin.user:
      append: true
      groups: sudo
      name: kadmin
    register: output
  - debug: var=output
  when: ansible_os_family=="Debian"
  #==== RedHat ====
- block:
  - name: install sudo,mc,net-tools,nano on RedHat
    yum:
      state: latest
      name:
        - sudo
        - mc
        - net-tools
        - nano
#        - xz-utils
      update_cache: yes
  - name: Set user into group wheel
    shell:
      cmd: /usr/sbin/usermod -aG wheel '{{ username }}'
    register: output
  - debug: var=output
  when: ansible_os_family=="RedHat"
...
