---
- name: Install kubernetes only on Debian
  hosts: "{{ hn }}"
  become: yes
  gather_facts: yes
  tasks:
     - name: Create containerd config file
       file:
         path: "/etc/modules-load.d/k8s.conf"
         state: "touch"

     - name: Add conf for containerd
       blockinfile:
         path: "/etc/modules-load.d/k8s.conf"
         block: |
               overlay
               br_netfilter

     - name: modprobe
       shell: |
               sudo modprobe overlay
               sudo modprobe br_netfilter


     - name: Set system configurations for Kubernetes networking
       file:
         path: "/etc/sysctl.d/k8s.conf"
         state: "touch"

     - name: Add conf for containerd
       blockinfile:
         path: "/etc/sysctl.d/k8s.conf"
         block: |
                net.bridge.bridge-nf-call-iptables = 1
                net.ipv4.ip_forward = 1
                net.bridge.bridge-nf-call-ip6tables = 1

     - name: Apply new settings
       command: sudo sysctl --system

     - name: Install some software on Debian
       ansible.builtin.apt:
          name:
            - apt-transport-https
            - ca-certificates
            - lsb-release
            - gnupg
            - curl
          state: latest
          update_cache: true

     - name: Add signing key download.docker.com on Debian
       ansible.builtin.apt_key:
          url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
          state: present

     - name: Add repository into sources list on Debian
       ansible.builtin.apt_repository:
          repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
          state: present
          filename: docker


     - name: Install containerd.io on Debian
       ansible.builtin.apt:
          name:
            - containerd.io
          state: latest
          update_cache: true

     - name: Config containerd
       shell: |
               mkdir -p /etc/containerd
               containerd config default | sudo tee /etc/containerd/config.toml
               sed -i 's/SystemdCgroup.*$/SystemdCgroup = true/g' /etc/containerd/config.toml
               # Change sandbox_pause version from 3.6 to 3.9
               sed -i 's/pause\:3\.6/pause\:3\.9/g' /etc/containerd/config.toml
               systemctl restart containerd

     - name: disable swap
       shell: |
               sudo swapoff -a
               sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

     - name: Add signing key dl.k8s.io on Debian
       ansible.builtin.apt_key:
          url: "https://dl.k8s.io/apt/doc/apt-key.gpg"
          state: present          


     - name: Add K8s Source
       ansible.builtin.apt_repository:
          repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main"
          state: present
          filename: kubernetes

     - name: Install kubelet,kubeadm,kubectl on Debian
       ansible.builtin.apt:
          name:
            - kubelet
            - kubeadm
            - kubectl
          state: latest
          update_cache: true

     - name: Prevent kubelet,kubeadm,kubectl from being upgraded
       ansible.builtin.dpkg_selections: 
         name: "{{ item }}"
         selection: hold
       loop:
          - kubelet
          - kubeadm
          - kubectl
