---
# tasks file for prepare_linux
- name: Before run playbook install_k8s.yml
  import_tasks: install_k8s.yml

- name: Install keepalived
  ansible.builtin.apt:
    name:
      - keepalived
      - haproxy
    state: present
    update_cache: true
  
- name: Copy config to /etc/keepalived/
  ansible.builtin.template:
    src: keepalived.j2
    dest: /etc/keepalived/keepalived.conf

- name: Copy configs to /etc/keepalived/
  ansible.builtin.template:
    src: check_apiserver.j2
    dest: /etc/keepalived/check_apiserver.sh
    mode: 0755

- name: Copy config to /etc/haproxy/
  ansible.builtin.template:
    src: haproxy.j2
    dest: /etc/haproxy/haproxy.cfg

- name: Set services keepalived and haproxy enabled
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
  loop:
    - keepalived
    - haproxy
...
