---
# vars file for test
# https://github.com/kubernetes/kubeadm/blob/main/docs/ha-considerations.md#kube-vip
# MASTER OR BACKUP
#STATE: MASTER
# Interface
#INTERFACE: ens03
# Any number
ROUTER_ID: 100
# MASTER is higher number, for exsample: MASTER: 101, BACKUP: 100
PRIORITY: 100
# some pass
AUTH_PASS: 123213213
# ip
APISERVER_VIP: 192.168.103.12
# default port
APISERVER_DEST_PORT: 6443
