---
# tasks file for prepare_linux
- name: Install keepalived
  ansible.builtin.apt:
    name:
      - keepalived
    state: present
    update_cache: true
  
- name: Copy configs to root
  ansible.builtin.template:
    src: 
  loop:
    - keepalived.j2
    - check_apiserver.j2

...
