---
- name: install Docker
  hosts: "{{ hn }}"
  become: true
  tasks:
#####
## BLOCK For Debian OS Family
#####
    - block:
      - name: Install apt-transport-https on Debian
        ansible.builtin.apt:
          name:
            - apt-transport-https
            - ca-certificates
            - lsb-release
            - gnupg
          state: latest
          update_cache: true

      - name: Add signing key on Debian
        ansible.builtin.get_url:
          url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
          dest: /etc/apt/keyrings/docker.asc
          mode: "0644"
          force: true

      - name: Add repository into sources list on Debian
        ansible.builtin.apt_repository:
          repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
          state: present
          filename: docker

      - name: Install Docker on Debian
        ansible.builtin.apt:
          name:
            - docker-ce
            - docker-ce-cli
            - containerd.io
            - docker-buildx-plugin
            - docker-compose-plugin
          state: latest
          update_cache: true
      when: ansible_facts['os_family'] == "Debian"
#####
## BLOCK for OracleLinux OS Family
#####
    - block:
      - name: set mydistribution on RedHat
        ansible.builtin.set_fact:
          mydistribution: "{{ 'rhel' if (ansible_distribution == 'Red Hat Enterprise Linux') else (ansible_distribution | lower) }}"

      - name: Add signing key on RedHat
        ansible.builtin.rpm_key:
          key: "https://download.docker.com/linux/centos/gpg"
          state: present

      - name: Add repository into repo.d list on RedHat
        ansible.builtin.shell:
          cmd: yum-config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
#          description: docker repository
#          baseurl: "https://download.docker.com/linux/{{ mydistribution }}/$releasever/$basearch/stable"
#          baseurl: "https://download.docker.com/linux/centos/docker-ce.repo/$releasever/$basearch/stable"
#          enabled: true
#          gpgcheck: true
#          gpgkey: "https://download.docker.com/linux/centos/gpg"

      - name: Install Docker
        ansible.builtin.yum:
          name:
            - docker-ce
            - docker-ce-cli
            - containerd.io
            - docker-buildx-plugin
            - docker-compose-plugin
          state: latest
          update_cache: true

      - name: Start Docker
        ansible.builtin.service:
          name: "docker"
          enabled: true
          state: started
      when: ansible_facts['os_family'] == "RedHat"
