---
- name: start role
  hosts: "{{ hn }}"
# We need use become-method: su, and good idea set PATH one more time
  environment:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  roles:
    - role: prepare_linux
    #- role: install_zabbix_agent
      when: ansible_facts['os_family'] == 'Debian'
